/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataBuku.java
 *
 * Created on Jun 4, 2013, 9:12:04 AM
 */
/**
 *
 * @author Robby Al Wahab13
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Daftarfb extends javax.swing.JFrame {
        String user="root";
        String pswd ="";
        String host="localhost";
        String db="Dbbuku";
        String url="";
        private Connection Lconnection=null;

    /** Creates new form DataBuku */
    public Daftarfb() {
        initComponents();
         btndelete.setEnabled(false);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" 
                    + user + "&password="+ pswd;

            Lconnection=DriverManager.getConnection(url);
        }

        catch(ClassNotFoundException e) {
            System.out.println("Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal:" +
                 e.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkodebuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpenerbit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpengarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttahun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtkota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        btnId = new javax.swing.JButton();
        btnnama = new javax.swing.JButton();
        btninput = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Buku");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selamat Datang di Facebook Aplikasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nama Account");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nama Depan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama Belakang");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Kota");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Negara");

        btnId.setText("Cek Email");
        btnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdActionPerformed(evt);
            }
        });

        btnnama.setText("Cek Nama");
        btnnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnamaActionPerformed(evt);
            }
        });

        btninput.setText("Input");
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btninput)
                .addGap(49, 49, 49)
                .addComponent(btndelete)
                .addGap(41, 41, 41)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtpengarang, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtpenerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnId, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnId)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnama))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninput)
                    .addComponent(btndelete)
                    .addComponent(btnedit)
                    .addComponent(btnexit))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        // TODO add your handling code here:
        
      
        try {
            Class.forName("com.mysql.jdbc.Driver");

            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);

            PreparedStatement pStatement = conn.prepareStatement("INSERT INTO tbbuku(Kode, Nama, Penerbit, Pengarang, Tahun, Kota, Judul)" + "VALUES (?,?,?,?,?,?,?)");

            pStatement.setString(1, txtkodebuku.getText());
            pStatement.setString(2, txtnama.getText());
            pStatement.setString(3, txtpenerbit.getText());
            pStatement.setString(4,  txtpengarang.getText());
            pStatement.setString(5, txttahun.getText());
            pStatement.setString(6, txtkota.getText());
            pStatement.setString(7, txtjudul.getText());

            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog(this,
                   "Penambahan sukses", "Informasi",
                   JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this,
                   "Penambahan gagal", "Informasi",
                   JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            txtkodebuku.setText("");
            txtnama.setText("");
            txtpenerbit.setText("");
            txtpengarang.setText("");
            txttahun.setText("");
            txtkota.setText("");
            txtjudul.setText("");
       }

       catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
       }

       catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

      }
    }//GEN-LAST:event_btninputActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         try {
            PreparedStatement pStatement = Lconnection.prepareStatement
                    ("DELETE FROM tbbuku WHERE Kode=?");

            pStatement.setString(1, txtkodebuku.getText());

            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog
               (this,"Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog
                (this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

            txtkodebuku.setText("");
            txtnama.setText("");
            txtpenerbit.setText("");
            txtpengarang.setText("");
            txttahun.setText("");
            txtkota.setText("");
            txtjudul.setText("");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from tbbuku" + " where Kode='" + txtkodebuku.getText() + "'");
            if (rs.next()) {
                btndelete.setEnabled(true);
                txtnama.setText(rs.getString("Nama"));
                txtpenerbit.setText(rs.getString("Penerbit"));
                txtpengarang.setText(rs.getString("Pengarang"));
                txttahun.setText(rs.getString("Tahun"));
                txtkota.setText(rs.getString("Kota"));
                txtjudul.setText(rs.getString("Judul"));
                txtkodebuku.setText(rs.getString("Kode"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

               btndelete.setEnabled(false);
               txtkodebuku.setText("");
               txtnama.setText("");
               txtpenerbit.setText("");
               txtpengarang.setText("");
               txttahun.setText("");
               txtkota.setText("");
               txtjudul.setText("");
               txtnama.requestFocus();
                
            }
        } catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }
    }//GEN-LAST:event_btnIdActionPerformed

    private void btnnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnamaActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery("Select * from tbbuku" + " where Nama like('%" + txtnama.getText() + "%')");

            if (rs.next()) {
               btndelete.setEnabled(true);
                txtnama.setText(rs.getString("Nama"));
                txtpenerbit.setText(rs.getString("Penerbit"));
                txtpengarang.setText(rs.getString("Pengarang"));
                txttahun.setText(rs.getString("Tahun"));
                txtkota.setText(rs.getString("Kota"));
                txtjudul.setText(rs.getString("Judul"));
                txtkodebuku.setText(rs.getString("Kode"));
                
            } else {
                JOptionPane.showMessageDialog(this,"Nama Salah: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

              btndelete.setEnabled(false);
               txtkodebuku.setText("");
               txtnama.setText("");
               txtpenerbit.setText("");
               txtpengarang.setText("");
               txttahun.setText("");
               txtkota.setText("");
               txtjudul.setText("");
               txtnama.requestFocus();
                
            }
        } catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }
    }//GEN-LAST:event_btnnamaActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
         try {
            PreparedStatement pStatement = Lconnection.prepareStatement
  ("UPDATE tbbuku SET Nama=?,Penerbit=?,Pengarang=?,Tahun=?, Kota=?, Judul=? WHERE Kode=?");

            pStatement.setString(1, txtnama.getText());
            pStatement.setString(2, txtpenerbit.getText());
            pStatement.setString(3, txtpengarang.getText());
            pStatement.setString(4, txttahun.getText());
            pStatement.setString(5, txtkota.getText());
             pStatement.setString(6, txtjudul.getText());
            pStatement.setString(7, txtkodebuku.getText());
            
            if ( pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog(this,"Edit sukses", 
                 "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Edit gagal",
                "Informasi", JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

         
               txtkodebuku.setText("");
               txtnama.setText("");
               txtpenerbit.setText("");
               txtpengarang.setText("");
               txttahun.setText("");
               txtkota.setText("");
               txtjudul.setText("");
               
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataBuku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnId;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btninput;
    private javax.swing.JButton btnnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables
}
